"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, ArrowLeft, ArrowRight, BarChart3, BookOpenCheck, Brain, CheckCircle2, Flag, Pencil, Plus, Target, Trash2, TrendingUp } from "lucide-react";
import { deleteJson, getJson, patchJson, postJson } from "@/lib/api";
import { useAuth } from "@/hooks/useAuth";

const METRICS = [
  ["puzzle_rating", "Puzzle rating"], ["chess_rating", "Online rating"], ["puzzle_accuracy", "Puzzle accuracy"],
  ["games_reviewed", "Games reviewed"], ["puzzles_solved", "Puzzles solved"]
];
const CLASS_COLORS = { Blunder: "bg-red-100 text-red-700", Mistake: "bg-orange-100 text-orange-700", Inaccuracy: "bg-amber-100 text-amber-700" };

function Metric({ icon: Icon, label, value, detail }) {
  return <div className="rounded-3xl border bg-white p-5 shadow-sm"><Icon size={20} className="text-zinc-500"/><p className="mt-4 text-3xl font-black">{value}</p><p className="mt-1 text-xs font-black uppercase tracking-wide text-zinc-500">{label}</p>{detail && <p className="mt-2 text-[11px] text-zinc-400">{detail}</p>}</div>;
}

export default function ImprovementDashboard() {
  const auth = useAuth(); const router = useRouter();
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const [editingId, setEditingId] = useState("");
  const [form, setForm] = useState({ title: "Reach my next rating milestone", metric: "puzzle_rating", target: "1300", deadline: "" });
  const load = () => getJson("/api/improvement").then(setData).catch(requestError => setError(requestError.message));
  useEffect(() => { if (auth.status === "anonymous") router.push("/login"); if (auth.status === "authenticated") load(); }, [auth.status, router]);
  const saveGoal = async event => { event.preventDefault(); setSaving(true); setError(""); try { const payload = { ...form, target: Number(form.target), deadline: form.deadline || null }; if (editingId) await patchJson(`/api/improvement/goals/${editingId}`, payload); else await postJson("/api/improvement/goals", payload); setEditingId(""); setForm(previous => ({ ...previous, title: "", deadline: "" })); await load(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const removeGoal = async id => { setSaving(true); try { await deleteJson(`/api/improvement/goals/${id}`); await load(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  if (!data && !error) return <main className="grid min-h-screen place-items-center bg-zinc-50 font-bold text-zinc-500">Building your training plan…</main>;

  const ratingValues = data?.ratingTrend?.map(point => point.rating) || []; const minRating = ratingValues.length ? Math.min(...ratingValues) - 10 : 0; const maxRating = ratingValues.length ? Math.max(...ratingValues) + 10 : 1;
  return <main className="min-h-screen bg-zinc-50 px-4 py-8 text-zinc-900"><div className="mx-auto max-w-6xl">
    <Link href="/player" className="mb-5 inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft size={17}/>Player Portal</Link>
    <header className="rounded-3xl bg-zinc-900 p-7 text-white shadow-xl"><div className="flex items-center gap-3"><Brain className="text-amber-300"/><div><p className="text-xs font-black uppercase tracking-[.2em] text-zinc-400">Personalized training</p><h1 className="text-3xl font-black">Improvement Dashboard</h1></div></div><p className="mt-3 max-w-2xl text-sm text-zinc-300">A single plan built from your puzzle results, tactical themes, online rating, and Stockfish game reviews.</p></header>
    {error && <p className="mt-5 rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}
    {data && <>
      <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><Metric icon={BookOpenCheck} label="Puzzle rating" value={data.summary.puzzleRating}/><Metric icon={TrendingUp} label="Online rating" value={data.summary.chessRating}/><Metric icon={Target} label="Puzzle accuracy" value={`${data.summary.puzzleAccuracy}%`}/><Metric icon={CheckCircle2} label="Puzzles solved" value={data.summary.puzzlesSolved}/><Metric icon={BarChart3} label="Games reviewed" value={data.summary.gamesReviewed}/><Metric icon={Activity} label="Costly moves" value={data.summary.costlyMoves}/></section>

      <section className="mt-6 grid gap-6 lg:grid-cols-[1.05fr_.95fr]">
        <div className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Tactical themes</h2><p className="mt-1 text-sm text-zinc-500">Combined accuracy from rated and coach-assigned puzzles.</p><div className="mt-5 space-y-4">{data.tacticalThemes.map(theme => <div key={theme.tag}><div className="mb-1 flex justify-between text-xs font-bold"><span>{theme.tag}</span><span>{theme.accuracy}% • {theme.attempts}</span></div><div className="h-3 overflow-hidden rounded-full bg-zinc-100"><div className={`h-full rounded-full ${theme.accuracy < 70 ? "bg-red-400" : theme.accuracy >= 80 ? "bg-emerald-500" : "bg-amber-400"}`} style={{ width: `${theme.accuracy}%` }}/></div></div>)}{!data.tacticalThemes.length && <p className="rounded-2xl border border-dashed p-6 text-center text-sm text-zinc-500">Solve tagged puzzles to reveal tactical strengths and weaknesses.</p>}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-red-50 p-4"><p className="text-xs font-black uppercase text-red-700">Focus areas</p><p className="mt-2 text-sm font-bold">{data.weaknesses.map(item => item.tag).join(", ") || "More data needed"}</p></div><div className="rounded-2xl bg-emerald-50 p-4"><p className="text-xs font-black uppercase text-emerald-700">Strengths</p><p className="mt-2 text-sm font-bold">{data.strengths.map(item => item.tag).join(", ") || "More data needed"}</p></div></div></div>
        <div className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Recommended next</h2><p className="mt-1 text-sm text-zinc-500">Highest-impact actions based on current evidence.</p><div className="mt-5 space-y-3">{data.recommendations.map(item => <Link key={`${item.type}-${item.title}`} href={item.href} className="group flex items-center justify-between rounded-2xl bg-zinc-50 p-4"><div><p className="font-black">{item.title}</p><p className="mt-1 text-xs text-zinc-500">{item.detail}</p></div><ArrowRight size={17} className="shrink-0 transition group-hover:translate-x-1"/></Link>)}{!data.recommendations.length && <div className="rounded-2xl bg-emerald-50 p-5 text-sm font-bold text-emerald-700">Your recent data shows no urgent weakness. Keep a balanced training routine.</div>}</div>{data.recommendedPuzzles.length > 0 && <div className="mt-5"><p className="text-xs font-black uppercase tracking-wide text-zinc-400">Matching puzzle themes</p><div className="mt-2 flex flex-wrap gap-2">{data.recommendedPuzzles.map(puzzle => <Link href="/puzzles" key={puzzle._id} className="rounded-full bg-amber-100 px-3 py-2 text-xs font-bold">{puzzle.title} • {puzzle.rating}</Link>)}</div></div>}</div>
      </section>

      <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Mistakes from game reviews</h2><div className="mt-4 space-y-3">{data.recentMistakes.map((move, index) => <div key={`${move.san}-${index}`} className="rounded-2xl bg-zinc-50 p-4"><div className="flex items-center justify-between gap-3"><p className="font-black">{move.san} <span className="text-xs text-zinc-400">→ {move.bestMove}</span></p><span className={`rounded-full px-2 py-1 text-[10px] font-black ${CLASS_COLORS[move.classification]}`}>{move.classification}</span></div><p className="mt-2 text-xs leading-5 text-zinc-500">{move.explanation || `${move.loss} centipawn loss. Review this position to understand the missed opportunity.`}</p></div>)}{!data.recentMistakes.length && <p className="rounded-2xl border border-dashed p-6 text-center text-sm text-zinc-500">Analyze completed games to identify recurring decision-making mistakes.</p>}</div></div>
        <div className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Online rating trend</h2><div className="mt-6 flex h-52 items-end gap-2 rounded-2xl bg-zinc-50 p-4">{data.ratingTrend.map((point, index) => { const height = 20 + ((point.rating - minRating) / Math.max(1, maxRating - minRating)) * 80; return <div key={`${point.playedAt}-${index}`} className="group relative flex h-full flex-1 items-end"><div className={`w-full rounded-t-md ${point.change >= 0 ? "bg-emerald-400" : "bg-red-400"}`} style={{ height: `${height}%` }}/><span className="absolute -top-1 left-1/2 hidden -translate-x-1/2 rounded bg-zinc-900 px-2 py-1 text-[9px] text-white group-hover:block">{point.rating}</span></div>; })}{!data.ratingTrend.length && <p className="m-auto text-center text-sm text-zinc-500">Complete rated online games to build a rating trend.</p>}</div></div></section>

      <section className="mt-6 rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Flag/><h2 className="text-xl font-black">Progress goals</h2></div><div className="mt-5 grid gap-4 md:grid-cols-2">{data.goals.map(goal => { const percentage = Math.min(100, Math.round(goal.current / goal.target * 100)); return <div key={goal._id} className={`rounded-2xl p-5 ${goal.completed ? "bg-emerald-50" : "bg-zinc-50"}`}><div className="flex items-start justify-between gap-3"><div><p className="font-black">{goal.title}</p><p className="mt-1 text-xs text-zinc-500">{goal.current} / {goal.target}{goal.deadline ? ` • Due ${new Date(goal.deadline).toLocaleDateString()}` : ""}</p></div><div className="flex"><button aria-label={`Edit ${goal.title}`} onClick={() => { setEditingId(goal._id); setForm({ title: goal.title, metric: goal.metric, target: String(goal.target), deadline: goal.deadline ? new Date(goal.deadline).toISOString().slice(0, 10) : "" }); }} disabled={saving} className="rounded-lg p-2 text-zinc-400 hover:bg-white hover:text-zinc-900"><Pencil size={16}/></button><button aria-label={`Remove ${goal.title}`} onClick={() => removeGoal(goal._id)} disabled={saving} className="rounded-lg p-2 text-zinc-400 hover:bg-white hover:text-red-600"><Trash2 size={16}/></button></div></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-white"><div className={`h-full rounded-full ${goal.completed ? "bg-emerald-500" : "bg-amber-400"}`} style={{ width: `${percentage}%` }}/></div><p className="mt-2 text-right text-[10px] font-black">{goal.completed ? "Completed" : `${percentage}%`}</p></div>})}</div>
        <form onSubmit={saveGoal} className="mt-5 grid gap-3 rounded-2xl border border-dashed p-4 md:grid-cols-[1.5fr_1fr_.7fr_1fr_auto]"><input aria-label="Goal title" required maxLength={100} value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} placeholder="Goal title" className="rounded-xl border p-3 text-sm"/><select aria-label="Goal metric" value={form.metric} disabled={Boolean(editingId)} onChange={event => setForm({ ...form, metric: event.target.value })} className="rounded-xl border p-3 text-sm disabled:bg-zinc-100">{METRICS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input aria-label="Goal target" required type="number" min="1" max="100000" value={form.target} onChange={event => setForm({ ...form, target: event.target.value })} className="rounded-xl border p-3 text-sm"/><input aria-label="Goal deadline" type="date" value={form.deadline} onChange={event => setForm({ ...form, deadline: event.target.value })} className="rounded-xl border p-3 text-sm"/><button disabled={saving} className="flex items-center justify-center gap-2 rounded-xl bg-zinc-900 px-5 py-3 text-xs font-black text-white disabled:opacity-50">{editingId ? <Pencil size={16}/> : <Plus size={16}/>} {editingId ? "Save" : "Add"}</button>{editingId && <button type="button" onClick={() => { setEditingId(""); setForm({ title: "", metric: "puzzle_rating", target: "1300", deadline: "" }); }} className="text-xs font-bold text-zinc-500 md:col-span-5">Cancel editing</button>}</form>
      </section>
    </>}
  </div></main>;
}
