"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Chess } from "chess.js";
import { ArrowLeft, BookOpen, Brain, CheckCircle2, ChevronRight, GraduationCap, Plus, RotateCcw, Save, Share2, Undo2 } from "lucide-react";
import { CHESS_PIECES } from "@/lib/chessPieces";
import { getJson, patchJson, postJson } from "@/lib/api";
import { useAuth } from "@/hooks/useAuth";

const FILES = ["a", "b", "c", "d", "e", "f", "g", "h"]; const RANKS = [8, 7, 6, 5, 4, 3, 2, 1];

function Board({ game, flipped, selected, targets, lastMove, onSquare }) {
  const ranks = flipped ? [...RANKS].reverse() : RANKS; const files = flipped ? [...FILES].reverse() : FILES;
  return <div className="flex aspect-square w-full flex-col overflow-hidden rounded-2xl border shadow-lg">{ranks.map((rank, row) => <div key={rank} className="flex flex-1">{files.map((file, col) => { const square = `${file}${rank}`; const piece = game.get(square); const highlighted = lastMove && (lastMove.from === square || lastMove.to === square); return <button type="button" aria-label={square} key={square} onClick={() => onSquare(square)} className={`relative flex flex-1 items-center justify-center ${(row + col) % 2 ? "bg-[#e2d5c3]" : "bg-[#f5f1ea]"} ${selected === square ? "ring-4 ring-inset ring-amber-500" : ""}`}>{highlighted && <span className="absolute inset-0 bg-amber-300/35"/>}{targets.includes(square) && <span className="absolute z-20 h-3 w-3 rounded-full bg-zinc-900/30"/>}{piece && <span className="relative z-10 h-[86%] w-[86%]"><Image src={CHESS_PIECES[piece.color][piece.type]} alt={`${piece.color} ${piece.type}`} fill unoptimized className="object-contain"/></span>}</button>; })}</div>)}</div>;
}

export default function OpeningRepertoiresPage() {
  const auth = useAuth(); const router = useRouter();
  const [repertoires, setRepertoires] = useState([]); const [classrooms, setClassrooms] = useState([]); const [selectedId, setSelectedId] = useState(""); const [view, setView] = useState("library"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const [newRep, setNewRep] = useState({ name: "", description: "", side: "white" }); const [lineLabel, setLineLabel] = useState("");
  const [editorGame, setEditorGame] = useState(() => new Chess()); const [editorMoves, setEditorMoves] = useState([]); const [selectedSquare, setSelectedSquare] = useState(null); const [targets, setTargets] = useState([]);
  const [practiceLineId, setPracticeLineId] = useState(""); const [practiceGame, setPracticeGame] = useState(() => new Chess()); const [practiceIndex, setPracticeIndex] = useState(0); const [practiceMistakes, setPracticeMistakes] = useState(0); const [practiceSelected, setPracticeSelected] = useState(null); const [practiceTargets, setPracticeTargets] = useState([]); const [feedback, setFeedback] = useState("");
  const [assignment, setAssignment] = useState({ classroomId: "", instructions: "", dueAt: "" });
  const load = async () => { const response = await getJson("/api/openings"); setRepertoires(response.repertoires); if (!selectedId && response.repertoires.length) setSelectedId(response.repertoires[0]._id); };
  useEffect(() => { if (auth.status === "anonymous") router.push("/login"); if (auth.status === "authenticated") { getJson("/api/openings").then(response => { setRepertoires(response.repertoires); if (response.repertoires.length) setSelectedId(current => current || response.repertoires[0]._id); }).catch(requestError => setError(requestError.message)); if (auth.user.role === "coach") getJson("/api/classrooms/coach").then(response => setClassrooms(response.classrooms)).catch(() => undefined); } }, [auth.status, auth.user?.role, router]);
  const repertoire = repertoires.find(item => item._id === selectedId); const practiceLine = repertoire?.lines.find(line => line._id === practiceLineId);
  const moveTree = useMemo(() => repertoire?.lines.map(line => ({ id: line._id, label: line.label, san: line.moves.map(move => move.san).join(" ") })) || [], [repertoire]);
  const resetEditor = () => { setEditorGame(new Chess()); setEditorMoves([]); setSelectedSquare(null); setTargets([]); };
  const editorClick = square => { const piece = editorGame.get(square); if (piece?.color === editorGame.turn()) { setSelectedSquare(square); setTargets(editorGame.moves({ square, verbose: true }).map(move => move.to)); return; } if (!selectedSquare || !targets.includes(square)) { setSelectedSquare(null); setTargets([]); return; } const next = new Chess(editorGame.fen()); const move = next.move({ from: selectedSquare, to: square, promotion: "q" }); setEditorGame(next); setEditorMoves(current => [...current, { from: move.from, to: move.to, promotion: move.promotion || "q", san: move.san }]); setSelectedSquare(null); setTargets([]); };
  const undoEditor = () => { if (!editorMoves.length) return; const nextMoves = editorMoves.slice(0, -1); const next = new Chess(); nextMoves.forEach(move => next.move(move)); setEditorMoves(nextMoves); setEditorGame(next); };
  const createRepertoire = async event => { event.preventDefault(); setSaving(true); setError(""); try { const response = await postJson("/api/openings", newRep); await load(); setSelectedId(response.repertoire._id); setNewRep({ name: "", description: "", side: "white" }); setView("editor"); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const saveLine = async () => { if (!repertoire || !lineLabel.trim() || !editorMoves.length) return; setSaving(true); try { const response = await postJson(`/api/openings/${repertoire._id}/lines`, { label: lineLabel, moves: editorMoves }); setRepertoires(current => current.map(item => item._id === repertoire._id ? { ...response.repertoire, isOwner: true, lines: response.repertoire.lines.map(line => ({ ...line, progress: { due: true, repetitions: 0, intervalDays: 0, lastGrade: 0 } })) } : item)); setLineLabel(""); resetEditor(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const startPractice = lineId => { setPracticeLineId(lineId); setPracticeGame(new Chess()); setPracticeIndex(0); setPracticeMistakes(0); setPracticeSelected(null); setPracticeTargets([]); setFeedback(""); setView("practice"); };
  const practiceClick = square => { if (!practiceLine || practiceIndex >= practiceLine.moves.length) return; const piece = practiceGame.get(square); if (piece?.color === practiceGame.turn()) { setPracticeSelected(square); setPracticeTargets(practiceGame.moves({ square, verbose: true }).map(move => move.to)); return; } if (!practiceSelected || !practiceTargets.includes(square)) { setPracticeSelected(null); setPracticeTargets([]); return; } const expected = practiceLine.moves[practiceIndex]; if (practiceSelected !== expected.from || square !== expected.to) { setPracticeMistakes(value => value + 1); setFeedback(`Try again. Move ${practiceIndex + 1} is not correct.`); setPracticeSelected(null); setPracticeTargets([]); return; } const next = new Chess(practiceGame.fen()); next.move({ from: practiceSelected, to: square, promotion: expected.promotion || "q" }); setPracticeGame(next); setPracticeIndex(value => value + 1); setPracticeSelected(null); setPracticeTargets([]); setFeedback(practiceIndex + 1 === practiceLine.moves.length ? "Line complete — rate your recall." : "Correct. Continue the line."); };
  const gradePractice = async grade => { setSaving(true); try { await postJson(`/api/openings/${repertoire._id}/practice`, { lineId: practiceLine._id, grade }); await load(); setFeedback("Review scheduled successfully."); setView("library"); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const publish = async () => { setSaving(true); try { await patchJson(`/api/openings/${repertoire._id}/publish`, { published: !repertoire.published }); await load(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const assign = async event => { event.preventDefault(); setSaving(true); try { await postJson(`/api/openings/${repertoire._id}/assign`, { ...assignment, dueAt: assignment.dueAt || null }); setAssignment({ classroomId: "", instructions: "", dueAt: "" }); await load(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };

  return <main className="min-h-screen bg-zinc-50 px-4 py-8 text-zinc-900"><div className="mx-auto max-w-6xl"><Link href="/player" className="mb-5 inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft size={17}/>Player Portal</Link><header className="rounded-3xl bg-zinc-900 p-7 text-white"><div className="flex items-center gap-3"><BookOpen className="text-amber-300"/><div><p className="text-xs font-black uppercase tracking-[.2em] text-zinc-400">Opening study</p><h1 className="text-3xl font-black">Repertoire Trainer</h1></div></div><p className="mt-3 text-sm text-zinc-300">Build move trees, memorize variations, and review each line when spaced repetition schedules it.</p></header>{error && <p className="mt-5 rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}
    <section className="mt-6 grid gap-6 lg:grid-cols-[320px_1fr]"><aside className="space-y-4"><form onSubmit={createRepertoire} className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="font-black">New repertoire</h2><input required maxLength={100} placeholder="e.g. Italian Game" value={newRep.name} onChange={event => setNewRep({ ...newRep, name: event.target.value })} className="mt-3 w-full rounded-xl border p-3 text-sm"/><textarea maxLength={500} placeholder="Study notes" value={newRep.description} onChange={event => setNewRep({ ...newRep, description: event.target.value })} className="mt-2 w-full rounded-xl border p-3 text-sm"/><select value={newRep.side} onChange={event => setNewRep({ ...newRep, side: event.target.value })} className="mt-2 w-full rounded-xl border p-3 text-sm"><option value="white">White repertoire</option><option value="black">Black repertoire</option></select><button disabled={saving} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-zinc-900 p-3 text-xs font-black text-white"><Plus size={15}/>Create</button></form><div className="rounded-3xl border bg-white p-3 shadow-sm"><p className="px-2 py-2 text-xs font-black uppercase text-zinc-400">Your library</p>{repertoires.map(item => <button key={item._id} onClick={() => { setSelectedId(item._id); setView("library"); }} className={`mb-2 w-full rounded-2xl p-4 text-left ${item._id === selectedId ? "bg-zinc-900 text-white" : "bg-zinc-50"}`}><div className="flex justify-between"><p className="font-black">{item.name}</p><span className="text-[10px] font-bold uppercase">{item.side}</span></div><p className="mt-1 text-xs opacity-60">{item.lines.length} lines • {item.dueLines} due</p>{item.assignment && <p className="mt-2 text-[10px] font-bold text-amber-500">Assigned: {item.assignment.classroom}</p>}</button>)}{!repertoires.length && <p className="p-5 text-center text-xs text-zinc-400">Create a repertoire or join a coach classroom.</p>}</div></aside>
      <div>{!repertoire ? <div className="rounded-3xl border border-dashed bg-white p-12 text-center"><Brain className="mx-auto text-zinc-400"/><h2 className="mt-3 text-xl font-black">Start your opening journey</h2><p className="mt-1 text-sm text-zinc-500">Create a repertoire, then record your first line visually.</p></div> : <><div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase text-amber-600">{repertoire.side} repertoire {repertoire.assignment ? `• ${repertoire.assignment.classroom}` : ""}</p><h2 className="mt-1 text-2xl font-black">{repertoire.name}</h2><p className="mt-1 text-sm text-zinc-500">{repertoire.description || "No description yet."}</p></div><div className="flex gap-2">{repertoire.isOwner && <button onClick={() => setView("editor")} className="rounded-xl border px-4 py-2 text-xs font-bold">Add line</button>}<button onClick={() => { const due = repertoire.lines.find(line => line.progress?.due) || repertoire.lines[0]; if (due) startPractice(due._id); }} disabled={!repertoire.lines.length} className="rounded-xl bg-amber-400 px-4 py-2 text-xs font-black disabled:opacity-40">Practice due ({repertoire.dueLines})</button></div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-zinc-50 p-3"><p className="text-xl font-black">{repertoire.lines.length}</p><p className="text-[10px] font-bold text-zinc-400">LINES</p></div><div className="rounded-2xl bg-zinc-50 p-3"><p className="text-xl font-black">{repertoire.dueLines}</p><p className="text-[10px] font-bold text-zinc-400">DUE</p></div><div className="rounded-2xl bg-zinc-50 p-3"><p className="text-xl font-black">{repertoire.masteredLines}</p><p className="text-[10px] font-bold text-zinc-400">MASTERED</p></div></div></div>
        {view === "library" && <div className="mt-5 rounded-3xl border bg-white p-6 shadow-sm"><h3 className="text-xl font-black">Move tree</h3><p className="mt-1 text-sm text-zinc-500">Each branch is trained and scheduled independently.</p><div className="mt-5 space-y-3">{moveTree.map((line, index) => { const source = repertoire.lines.find(item => item._id === line.id); return <button onClick={() => startPractice(line.id)} key={line.id} className="flex w-full items-center justify-between rounded-2xl bg-zinc-50 p-4 text-left"><div className="min-w-0"><p className="font-black"><span className="mr-2 text-amber-600">{index + 1}.</span>{line.label}</p><p className="mt-1 truncate text-xs text-zinc-500">{line.san}</p><p className="mt-2 text-[10px] font-bold text-zinc-400">Interval {source.progress?.intervalDays || 0}d • {source.progress?.due ? "Due now" : `Due ${new Date(source.progress.dueAt).toLocaleDateString()}`}</p></div><ChevronRight className="shrink-0" size={18}/></button>})}{!moveTree.length && <p className="rounded-2xl border border-dashed p-8 text-center text-sm text-zinc-500">No lines yet. Add the main variation first.</p>}</div></div>}
        {view === "editor" && repertoire.isOwner && <div className="mt-5 grid gap-5 rounded-3xl border bg-white p-5 shadow-sm md:grid-cols-[minmax(0,520px)_1fr]"><Board game={editorGame} flipped={repertoire.side === "black"} selected={selectedSquare} targets={targets} lastMove={editorMoves.at(-1)} onSquare={editorClick}/><div><h3 className="text-xl font-black">Visual line editor</h3><p className="mt-1 text-sm text-zinc-500">Play the complete variation on the board. Every move is legally validated again by the server.</p><input placeholder="Line name, e.g. Main line" value={lineLabel} onChange={event => setLineLabel(event.target.value)} className="mt-4 w-full rounded-xl border p-3 text-sm"/><div className="mt-3 min-h-24 rounded-2xl bg-zinc-50 p-4"><p className="text-xs font-black uppercase text-zinc-400">Recorded line</p><p className="mt-2 text-sm font-bold">{editorMoves.map(move => move.san).join(" ") || "Play moves on the board."}</p></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={undoEditor} disabled={!editorMoves.length} className="flex items-center justify-center gap-2 rounded-xl border p-3 text-xs font-bold disabled:opacity-40"><Undo2 size={16}/>Undo</button><button onClick={saveLine} disabled={!editorMoves.length || !lineLabel.trim() || saving} className="flex items-center justify-center gap-2 rounded-xl bg-zinc-900 p-3 text-xs font-black text-white disabled:opacity-40"><Save size={16}/>Save line</button></div></div></div>}
        {view === "practice" && practiceLine && <div className="mt-5 grid gap-5 rounded-3xl border bg-white p-5 shadow-sm md:grid-cols-[minmax(0,520px)_1fr]"><Board game={practiceGame} flipped={repertoire.side === "black"} selected={practiceSelected} targets={practiceTargets} lastMove={practiceIndex ? practiceLine.moves[practiceIndex - 1] : null} onSquare={practiceClick}/><div><p className="text-xs font-black uppercase text-amber-600">Spaced repetition</p><h3 className="mt-1 text-xl font-black">{practiceLine.label}</h3><p className="mt-2 text-sm text-zinc-500">Recall the complete branch from memory. Move {Math.min(practiceIndex + 1, practiceLine.moves.length)} of {practiceLine.moves.length}.</p><div className="mt-4 h-3 overflow-hidden rounded-full bg-zinc-100"><div className="h-full bg-amber-400" style={{ width: `${practiceIndex / practiceLine.moves.length * 100}%` }}/></div>{feedback && <p className="mt-4 rounded-2xl bg-zinc-50 p-4 text-sm font-bold">{feedback}</p>}<p className="mt-3 text-xs text-zinc-400">Mistakes this session: {practiceMistakes}</p>{practiceIndex === practiceLine.moves.length && <div className="mt-5"><p className="text-xs font-black uppercase text-zinc-400">How well did you remember it?</p><div className="mt-2 grid grid-cols-3 gap-2"><button onClick={() => gradePractice(1)} className="rounded-xl bg-red-100 p-3 text-xs font-black text-red-700">Again</button><button onClick={() => gradePractice(3)} className="rounded-xl bg-amber-100 p-3 text-xs font-black text-amber-700">Hard</button><button onClick={() => gradePractice(5)} className="rounded-xl bg-emerald-100 p-3 text-xs font-black text-emerald-700">Easy</button></div></div>}<button onClick={() => startPractice(practiceLine._id)} className="mt-4 flex items-center gap-2 text-xs font-bold text-zinc-500"><RotateCcw size={14}/>Restart line</button></div></div>}
        {auth.user?.role === "coach" && repertoire.isOwner && <div className="mt-5 rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="text-xl font-black">Coach assignment</h3><p className="mt-1 text-sm text-zinc-500">Publish this repertoire before assigning it.</p></div><button onClick={publish} disabled={!repertoire.lines.length || saving} className="flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-bold"><Share2 size={15}/>{repertoire.published ? "Unpublish" : "Publish"}</button></div>{repertoire.published && <form onSubmit={assign} className="mt-5 grid gap-3 md:grid-cols-2"><select required value={assignment.classroomId} onChange={event => setAssignment({ ...assignment, classroomId: event.target.value })} className="rounded-xl border p-3 text-sm"><option value="">Select classroom</option>{classrooms.map(room => <option value={room._id} key={room._id}>{room.name}</option>)}</select><input type="date" value={assignment.dueAt} onChange={event => setAssignment({ ...assignment, dueAt: event.target.value })} className="rounded-xl border p-3 text-sm"/><textarea placeholder="Study instructions" value={assignment.instructions} onChange={event => setAssignment({ ...assignment, instructions: event.target.value })} className="rounded-xl border p-3 text-sm md:col-span-2"/><button className="flex items-center justify-center gap-2 rounded-xl bg-zinc-900 p-3 text-xs font-black text-white md:col-span-2"><GraduationCap size={16}/>Assign repertoire</button></form>}</div>}
      </>}</div></section>
  </div></main>;
}
