import Link from "next/link";
import { ArrowUpRight, BrainCircuit, Crown, ShieldCheck } from "lucide-react";
import FuturisticChessBoard from "@/components/FuturisticChessBoard";

export default function HomePage() {
  return <main className="min-h-screen overflow-hidden bg-[#080d17] text-slate-100">
    <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_15%_15%,rgba(42,101,139,.28),transparent_30%),radial-gradient(circle_at_85%_12%,rgba(180,126,67,.18),transparent_23%),linear-gradient(135deg,#080d17,#101c2d_55%,#090e18)]" />
    <div className="relative mx-auto max-w-7xl px-5 pb-16 pt-5 sm:px-8 lg:px-10">
      <nav className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.035] px-4 py-3 backdrop-blur-xl"><Link href="/" className="flex items-center gap-2 font-bold tracking-tight"><span className="grid size-8 place-items-center rounded-lg bg-amber-300 text-slate-950"><Crown size={17} /></span>Quiet Chess</Link><div className="flex items-center gap-2"><Link href="/login" className="rounded-xl px-3 py-2 text-sm font-semibold text-slate-300 transition hover:text-white">Sign in</Link><Link href="/signup" className="rounded-xl bg-white px-3 py-2 text-sm font-bold text-slate-950">Join free</Link></div></nav>
      <section className="grid items-center gap-12 pb-14 pt-16 lg:grid-cols-[.95fr_1.05fr] lg:pb-24 lg:pt-24"><div><p className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[.24em] text-amber-300"><span className="size-2 rounded-full bg-amber-300 shadow-[0_0_18px_#d4a359]" /> Play with clarity</p><h1 className="max-w-xl text-5xl font-semibold tracking-[-.055em] text-white sm:text-6xl lg:text-7xl">A calmer way to <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-200 to-cyan-200">think in chess.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-400">Play, analyse, and improve in a focused space built around the board — not distractions.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/signup" className="group flex items-center gap-2 rounded-2xl bg-amber-300 px-5 py-3.5 text-sm font-bold text-slate-950 shadow-lg shadow-amber-300/10 transition hover:bg-amber-200">Start playing <ArrowUpRight size={17} className="transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></Link><Link href="/login" className="rounded-2xl border border-white/15 bg-white/[.04] px-5 py-3.5 text-sm font-semibold text-white backdrop-blur transition hover:bg-white/[.08]">Open your dashboard</Link></div><div className="mt-12 grid max-w-lg grid-cols-3 gap-3">{[["01", "Focused board"], ["02", "Gentle analysis"], ["03", "Real progress"]].map(([number, label]) => <div key={number} className="rounded-2xl border border-white/10 bg-white/[.035] p-3"><p className="font-mono text-xs text-amber-300">{number}</p><p className="mt-3 text-xs font-medium leading-5 text-slate-300">{label}</p></div>)}</div></div><FuturisticChessBoard /></section>
      <section className="grid gap-3 md:grid-cols-3">{[[BrainCircuit, "Thoughtful analysis", "See useful insights when you need them — never while you are trying to think."], [ShieldCheck, "Quiet by design", "No flashing badges, intrusive feeds, or noisy competition for your attention."], [Crown, "Built to improve", "Train tactics, opening lines, and practical decision-making in one place."]].map(([Icon, title, description]) => <article key={title} className="rounded-3xl border border-white/10 bg-white/[.035] p-5 backdrop-blur"><Icon size={20} className="text-amber-300" /><h2 className="mt-6 font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{description}</p></article>)}</section>
    </div>
  </main>;
}
