"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ChevronLeft, ChevronRight } from "lucide-react";
import { Chess } from "chess.js";
import { CHESS_PIECES } from "@/lib/chessPieces";
import { analyzeGame, reviewSummary } from "@/lib/gameReview";
import { getJson, patchJson } from "@/lib/api";

const FILES = ["a", "b", "c", "d", "e", "f", "g", "h"]; const RANKS = [8, 7, 6, 5, 4, 3, 2, 1];
const CLASS_STYLES = { Brilliant: "bg-cyan-100 text-cyan-800", Best: "bg-emerald-100 text-emerald-800", Excellent: "bg-green-100 text-green-800", Good: "bg-blue-100 text-blue-800", Inaccuracy: "bg-amber-100 text-amber-800", Mistake: "bg-orange-100 text-orange-800", Blunder: "bg-red-100 text-red-800" };
const formatEvaluation = value => Math.abs(value) >= 90_000 ? `M${Math.max(1, Math.round((100_000 - Math.abs(value)) / 1000))}` : `${value >= 0 ? "+" : ""}${(value / 100).toFixed(2)}`;

export default function GameReviewPage() {
  const [record, setRecord] = useState(null); const [results, setResults] = useState([]); const [selectedIndex, setSelectedIndex] = useState(-1); const [progress, setProgress] = useState({ done: 0, total: 0 }); const [error, setError] = useState(""); const [saveWarning, setSaveWarning] = useState("");
  useEffect(() => {
    let cancelled = false;
    Promise.resolve().then(async () => {
      try { const gameId = new URLSearchParams(location.search).get("gameId"); let parsed; let storedReview = []; let storedVersion = 0; if (gameId) { const response = await getJson(`/api/games/${gameId}`); storedReview = response.game.review; storedVersion = response.game.reviewVersion || 0; parsed = { gameId: response.game._id, moves: response.game.moves, result: response.game.result, mode: response.game.mode, difficulty: response.game.difficulty, timeControl: response.game.timeControl }; } else { const saved = sessionStorage.getItem("chess:last-game-review"); if (!saved) throw new Error("No completed game is available for review."); parsed = JSON.parse(saved); } if (!parsed.moves?.length) throw new Error("This game has no moves to analyze."); if (cancelled) return; setRecord(parsed); if (storedVersion >= 2 && storedReview?.length === parsed.moves.length) { setResults(storedReview); setSelectedIndex(storedReview.length - 1); return; } setProgress({ done: 0, total: parsed.moves.length }); const analysis = await analyzeGame(parsed.moves, (done, total) => { if (!cancelled) setProgress({ done, total }); }); if (!cancelled) { setResults(analysis); setSelectedIndex(analysis.length - 1); if (parsed.gameId) patchJson(`/api/games/${parsed.gameId}/review`, { review: analysis, reviewVersion: 2 }).catch(reviewError => setSaveWarning(reviewError.message)); } }
      catch (reviewError) { if (!cancelled) setError(reviewError.message); }
    });
    return () => { cancelled = true; };
  }, []);
  if (error) return <main className="grid min-h-screen place-items-center bg-zinc-50 p-5"><div className="rounded-3xl border bg-white p-8 text-center"><p className="text-red-600">{error}</p><Link href="/new-game" className="mt-5 inline-block rounded-xl bg-zinc-900 px-5 py-3 text-sm font-bold text-white">Start a game</Link></div></main>;
  if (!record || results.length !== record.moves.length) { const percentage = progress.total ? Math.round(progress.done / progress.total * 100) : 0; return <main className="grid min-h-screen place-items-center bg-zinc-50 p-5"><div className="w-full max-w-md rounded-3xl border bg-white p-8 text-center shadow-sm"><h1 className="text-2xl font-black">Analyzing game…</h1><p className="mt-2 text-sm text-zinc-500">Comparing every move with the engine’s preferred continuation.</p><div className="mt-6 h-3 overflow-hidden rounded-full bg-zinc-100"><div className="h-full bg-amber-400 transition-all" style={{ width: `${percentage}%` }}/></div><p className="mt-3 text-xs font-bold">{progress.done}/{progress.total || "—"} moves</p></div></main>; }
  const selected = results[selectedIndex]; const boardGame = selectedIndex < 0 ? new Chess() : new Chess(selected.fen); const summary = reviewSummary(results); const whitePercent = Math.max(5, Math.min(95, 50 + (selected?.evaluation || 0) / 20));
  return <main className="min-h-screen bg-zinc-50 px-4 py-7 text-zinc-900"><div className="mx-auto max-w-6xl"><div className="mb-5 flex gap-4"><Link href="/games" className="inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft size={17}/>Game history</Link><Link href="/new-game" className="text-sm font-bold text-zinc-500">New game</Link></div>
    <header className="mb-6 rounded-3xl bg-zinc-900 p-7 text-white"><p className="text-xs font-black uppercase tracking-[.2em] text-amber-300">Engine review</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black">{record.result?.winner === "Draw" ? "Draw" : `${record.result?.winner} won`}</h1><p className="mt-1 text-sm text-zinc-400">{record.mode} game • {record.difficulty} • {record.result?.reason}</p></div><div className="flex gap-5"><div><p className="text-2xl font-black">{summary.whiteAccuracy}%</p><p className="text-xs text-zinc-400">White accuracy</p></div><div><p className="text-2xl font-black">{summary.blackAccuracy}%</p><p className="text-xs text-zinc-400">Black accuracy</p></div></div></div></header>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,620px)_1fr]"><section><div className="flex gap-3"><div className="relative flex w-9 flex-col overflow-hidden rounded-full border bg-white"><div className="bg-zinc-900 transition-all" style={{ height: `${100 - whitePercent}%` }}/><div className="bg-white" style={{ height: `${whitePercent}%` }}/><span className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded bg-zinc-700 px-1 py-0.5 text-[8px] font-black text-white">{formatEvaluation(selected?.evaluation || 0)}</span></div><div className="flex aspect-square flex-1 flex-col overflow-hidden rounded-2xl border shadow-lg">{RANKS.map((rank, row) => <div key={rank} className="flex flex-1">{FILES.map((file, col) => { const square = `${file}${rank}`; const piece = boardGame.get(square); const highlighted = selected && (selected.from === square || selected.to === square); return <div key={square} className={`relative flex flex-1 items-center justify-center ${(row + col) % 2 ? "bg-[#b58863]" : "bg-[#f0d9b5]"}`}>{highlighted && <span className="absolute inset-0 bg-amber-300/50"/>}{piece && <span className="relative h-[86%] w-[86%]"><Image src={CHESS_PIECES[piece.color][piece.type]} alt={`${piece.color} ${piece.type}`} fill unoptimized className="object-contain"/></span>}</div>; })}</div>)}</div></div>
      <div className="mt-4 flex items-center justify-between rounded-2xl border bg-white p-3"><button type="button" aria-label="Previous move" onClick={() => setSelectedIndex(current => Math.max(-1, current - 1))} disabled={selectedIndex < 0} className="rounded-xl p-2 disabled:opacity-30"><ChevronLeft/></button><div className="px-2 text-center">{selected ? <><span className={`rounded-full px-3 py-1 text-xs font-black ${CLASS_STYLES[selected.classification]}`}>{selected.classification}</span><p className="mt-2 text-sm font-bold">{selected.color === "w" ? `${selected.moveNumber}.` : `${selected.moveNumber}...`} {selected.san} • {selected.loss} cp loss</p><p className="text-xs text-zinc-500">Engine choice: {selected.bestMove} • Evaluation {formatEvaluation(selected.evaluation)}</p></> : <p className="font-bold">Starting position</p>}</div><button type="button" aria-label="Next move" onClick={() => setSelectedIndex(current => Math.min(results.length - 1, current + 1))} disabled={selectedIndex === results.length - 1} className="rounded-xl p-2 disabled:opacity-30"><ChevronRight/></button></div>
      {selected && <div className="mt-3 rounded-2xl border bg-white p-5"><h3 className="text-sm font-black">Coach explanation</h3><p className="mt-2 text-sm leading-6 text-zinc-600">{selected.explanation}</p><div className="mt-4 rounded-xl bg-zinc-50 p-3"><p className="text-[10px] font-black uppercase tracking-widest text-zinc-400">Best continuation</p><p className="mt-1 text-sm font-bold">{selected.bestLine?.length ? selected.bestLine.join(" ") : selected.bestMove}</p></div></div>}
    </section>
    <aside className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Move analysis</h2>{saveWarning && <p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs font-bold text-amber-800">Review displayed, but saving failed: {saveWarning}</p>}<div className="mt-4 flex flex-wrap gap-2">{Object.entries(summary.counts).map(([label, count]) => <span key={label} className={`rounded-full px-3 py-1 text-xs font-black ${CLASS_STYLES[label]}`}>{count} {label}</span>)}</div><div className="mt-6 grid grid-cols-2 gap-2">{results.map(move => <button type="button" onClick={() => setSelectedIndex(move.index)} key={move.index} className={`flex items-center justify-between rounded-xl border p-3 text-left ${selectedIndex === move.index ? "border-zinc-900 ring-2 ring-zinc-900/10" : ""}`}><span className="text-sm font-black">{move.color === "w" ? `${move.moveNumber}.` : `${move.moveNumber}...`} {move.san}</span><span className={`rounded-full px-2 py-1 text-[9px] font-black ${CLASS_STYLES[move.classification]}`}>{move.classification}</span></button>)}</div></aside></div>
  </div></main>;
}
